name: Scrape Bed Availability

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - name: Commit results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data.json
        git commit -m 'Update bed availability data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
