name: Daily Bed Availability Scraper

on:
  schedule:
    - cron: '0 10 * * *'  # Every day at 10:00 UTC
  workflow_dispatch:      # Manual trigger

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run scraper (Playwright)
        run: python scrape_beds.py

      # - name: Run Discord bot
      #   env:
      #     DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      #     USER_ID: ${{ secrets.USER_ID }}
      #   run: python bot_script.py

      - name: Commit updated data (if changed)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add bed_data.csv previous_bed_data.csv || true
          git commit -m "Daily update of bed data" || echo "No changes to commit"
          git push || echo "No changes to push"
